project:
  type: website
  output-dir: .quarto/output
  preview:
    port: 5000
  render:
    - README.md
    - notebooks

format:
  html:
    anchor-sections: true
    smooth-scroll: true
    theme: litera

website:
  title: Datadex
  repo-url: https://github.com/davidgasquez/datadex
  repo-actions: [edit, issue]
  page-footer: Made with ❤️ by David Gasquez
  navbar:
    search: true
    logo: https://em-content.zobj.net/thumbs/120/google/350/package_1f4e6.png
    left:
      - text: dbt Docs
        icon: sun
        file: docs
      - text: Knowledge Base
        icon: book
        href: notebooks
      - text: Evidence
        icon: book
        href: reports/build/
    tools:
      - icon: twitter
        href: https://twitter.com/davidgasquez
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/davidgasquez/datadex
          - text: Create an Issue
            url:  https://github.com/davidgasquez/datadex/issues/new
