project:
  type: website
  output-dir: .quarto/output
  preview:
    port: 5000
  render:
    - README.md
    - notebooks
    - dashboard.qmd
    - docs

format:
  html:
    anchor-sections: true
    smooth-scroll: true
    theme: litera

website:
  title: Datadex
  repo-url: https://github.com/davidgasquez/datadex
  repo-actions: [edit, issue]
  page-footer: Made with ❤️ by David Gasquez
  navbar:
    search: true
    logo: https://em-content.zobj.net/thumbs/120/google/350/package_1f4e6.png
    left:
      - text: dbt Docs
        icon: sun
        file: dbt
      - text: Dashboard
        icon: clipboard-data
        href: dashboard.html
      - text: Knowledge Base
        icon: book
        href: notebooks
      - text: Tutorial
        icon: bi-journal
        href: docs/tutorial.html
    tools:
      - icon: twitter
        href: https://twitter.com/davidgasquez
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/davidgasquez/datadex
          - text: Create an Issue
            url: https://github.com/davidgasquez/datadex/issues/new
